In [119]:
from PIL import Image
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy.spatial import distance
import random 




Xdelta=np.zeros([2400,784])
x = [ i for i in range(1,2401)]
x1=np.ones([2400])
filelist =list(map(str,x))

for imagefile in filelist:
    im=Image.open("F:\Semester 9\ML\Assignment3\Images/"+imagefile+".JPG")
    arrayimage =im.convert("L")
    imgarray = np.array(arrayimage)
    imgarray=imgarray.reshape(28*28)
    Xdelta[int(imagefile)-1][0:784]=imgarray
    
with open("F:\Semester 9\ML\Assignment3\Images/TestLabels.txt", "r") as f:
    TestLabels = [int(x) for x in f.read().split()]

for i in range(0,2400):
    for j in range(0,784):
        if(Xdelta[i][j]>140):
            Xdelta[i][j]=1
        else:
            Xdelta[i][j]=0
    
    
    
means = np.zeros([10,784])
rand1 = random.randint(0, 2400)
mean1 = Xdelta[rand1]
means[0]= mean1
maxd = 0


            
        
for j in range(1,10):
    for i in range(0,2400):
        d = distance.euclidean(Xdelta[i], means[j-1])
        if(d>maxd):
            maxd = distance.euclidean(Xdelta[i], means[j-1])
            nextmean = Xdelta[i]  
            mylasti = i
    means[j]= nextmean
    np.delete(Xdelta, mylasti, 0)    
print(means)




[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [121]:
means

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])